// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] as string,
    // @ts-expect-error directUrl is valid at runtime but missing from Prisma 7 type definitions
    directUrl: process.env["DIRECT_URL"] as string,
  },
});
